SELECT    P.CODPROD
        , P.DESCRICAO
        , D.*
        , P.CODEPTO
        , P.CODSEC
        , P.CODPRODPRINC
        , P.CODFILIAL
     FROM PCPRODUT P
        , PCDESCONTOFIDELIDADE D
    WHERE (D.CODPROD <> P.CODPRODPRINC
      AND D.CODPROD = P.CODPROD
      AND P.CODPRODPRINC = :CODPROD
      AND D.PERCDESCONTO = :PERCDESCONTO
      AND D.DTINICIAL = :DTINICIAL
      AND D.DTFINAL = :DTFINAL
      and D.dtExclusao is null) AND D.CODFILIAL = :CODFILIAL